### ISSUE TITLE
Project is not working on Windows

### ISSUE THREAD

**Issue by amitgandhi** [FriendsOfCake/crud-demo-app#1]
Hello,

I am trying to get your demo working on my local

Following are my machine details:
Windows 7
PHP Version 5.5.11
Composer version d036b2390ec18a78fc00f736ba8a08718afcf431 2014-06-09 17:36:06

I executed below command & getting error as InvalidArgumentException after project is created. Hence, autoloader.php is not getting created under vendor folder.

composer create-project -s dev friendsofcake/crud-demo-app

Below is console output:

D:\amit\xampp5\htdocs\projects>composer create-project -s dev friendsofcake/crud
-demo-app
Installing friendsofcake/crud-demo-app (dev-master ac51086ebfea238ca6ef916435841
72466ba657a)
  - Installing friendsofcake/crud-demo-app (dev-master master)
    Cloning master

Created project in D:\amit\xampp5\htdocs\projects\crud-demo-app

  [InvalidArgumentException]
  Composer could not find the config file: C:\ProgramData\ComposerSetup\bin\
  To initialize a project, please create a composer.json file as described in
   the http://getcomposer.org/ "Getting Started" section

create-project [-s|--stability="..."] [--prefer-source] [--prefer-dist] [--repos
itory-url="..."] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--n
o-scripts] [--no-progress] [--keep-vcs] [--no-install] [package] [directory] [ve
rsion]

**Comment by anhtuank7c** [comment]
I do use windows 7, but no problem.
I just remove slash from command: `php -S 0.0.0.0:9999 webroot index.php` and everything work well.

**Comment by josegonzalez** [comment]
I was also unable to replicate this on a Windows 7 vm. If you are still seeing this issue, please comment again on this thread. Sorry!
